# Header templates for different banks asset classes
UBS_asset_header_template = [
    "Number/Amount",
    "Description",
    "ISIN",
    "Sustainability (SI)",
    "S&P/Moody's rating",
    "Sector",
    "Duration",
    "Yield",
    "Cost price",
    "Cost Exchange rate",
    "Cost value",
    "Last purchase",
    "Perf. start date",
    "Market price",
    "Market Exchange rate",       
    "Market price date",
    "YTD performance",
    "Market gain",
    "Exchange gain",
    "Unrealized P/L",
    "Market value in USD",
    "Accrued interest in USD",
    "% NA"
] 
SC_asset_header_template = [
    "Currency",
    "Balance/Quantity",
    "ISIN",
    "Description",
    "Average purchase price",
    "Yield to maturity",
    "Price/Mark to market value",
    "As of date",
    "Valuation",
    "Reference currency valuation(USD)",
    "Weight(%)",
    "Performance instrument ccy(%)",
    "Reference ccy(%)",
]
JP_asset_header_template = []
BOS_asset_header_template = []
LGT_asset_header_template = [
    "Currency",
    "Units",
    "Designation",
    "Country",
    "S&P rating/Moody’s rating",
    "ISIN",
    "Security no."
    "Bloomberg ticker",
    "Sector (GICS)",
    "Mod. dur.",
    "Ytm",
    "Purchase price",
    "Purchase fx rate",
    "Purchase date",
    "Current price",
    "Current fx rate",
    "Current date",
    "Value in USD",
    "Amount in USD",
    "Accr. int. in USD",
    "Amount in curr.",
    "Accr. int. in curr.",
    "Balance in currency",
    "Accrued int, in curr.",
    "Balance in USD",
    "Accr. int. USD",
    "pl_total_asset_pct",
    "pl_total_fx_pct",
    "pl_total_pct",
    "pl_ytd_asset_pct",
    "pl_ytd_fx_pct",
    "pl_ytd_pct",
    "% of portf.",
    "Sustainability"
]
UOB_asset_header_template = []
UBP_asset_header_template = [
    "UNITS/NOMINAL",
    "SECURITY NAME",
    "ISIN/SECUR. NO.",
    "DURATION RATING",
    "ESG: PREVIOUS",
    "ESG: CURRENT",
    "YIELD/AV.PU.PRI",
    "MATURITY DATE"
    "RATE/PURCHASE PRICE",
    "NET AVERAGE COST",
    "MARKET PRICE",
    "TOTAL MARKET VALUE",
    "ACCRUED INTEREST",
    "MARKET VALUE IN USD",
    "ACCRUED INTEREST IN USD",
    "% ASSETS",
]
JSS_asset_header_template = [
    "Name",
    "ISIN"
    "ISIN/Sec. no.",
    "Bloomberg/Reuters",
    "Sector/Country",
    "Notional",
    "Currency",
    "Risk Currency",
    "Redemption",
    "Coupon date",
    "YTM%",
    "Rating",
    "Agency",
    "MODD",
    "Purchase Price",
    "Purchase FX rate",
    "Purchase Last date",
    "Current Price",
    "Current FX rate",
    "Current (Price date)",
    "Current Factor",
    "Profit/Loss Price%",
    "Profit/Loss FX%",
    "Profit/Loss Total%",
    "Profit/Loss Total USD",
    "Valuation",
    "Valuation in USD",
    "Accrued interest",
    "Accured interest in USD",
    "Allocation in %",
]
CAI_asset_header_template = [
  "CLOSING BAL.",
  "OPENING BAL.",
  "SECURITY NAME",
  "PREVIOUS PRC",
  "CURRENT PRC",
  "SECUR. NO.",
  "RATING",
  "ESG RATING",
  "MATURITY DATE",
  "RATE/PURCHASE PRICE",
  "YIELD/EST. PRI",
  "NET AVERAGE COST",
  "MARKET PRICE",
  "TOTAL MARKET VALUE",
  "ACCRUED INTEREST",
  "VALUE IN USD",
  "% ASSETS"
]
VPB_asset_header_template = [
    "Curr.",
    "Nominal",
    "Number",
    "Account",
    "ISIN",
    "Description",
    "Prc.date",
    "Maturity",
    "Purch.price",
    "Exch.rate",
    "Cost price in USD",
    "Market price",
    "Exch.rate",
    "Market value in USD",
    "Accr.in. in USD",
    "%",
    "Profit*",
    "Profit MWR*"
]
MSP_asset_header_template = [
    "Shares or Face Value",
    "Security Description",
    "PRR",
    "CCY",
    "Avg Price/FX Rate",  
    "Total Cost",
    "Mkt Price/FX Mkt Rt",
    "MarketValue",
    "Mkt P/(L)",
    "Mkt P/(L) %",
    "Forex P/(L)",
    "Accrued Income",
    "Total Mkt Value in USD",
    "% of Portfolio",
    "Acct Type",
]
UKH_asset_header_template = [
    "Date Acquired",
    "Description",
    "ISIN",
    "Quantity",
    "Unit Cost",
    "Current Cost Basis",
    "Market Price",
    "Market Value",
    "Unrealized Gain/Loss",
    "Estimated Annual Income",
    "Estimated Yield %",
]    

UBS_trans_header_template = [
    "Trade date",
    "Trade time",
    "Value date",
    "Booking text",
    "Tax",
    "Various",
    "Brokerage",
    "Number/Amount",
    "Custody account",
    "Account",
    "Stock exchange",
    "Description",
    "Cost Exchange rate",
    "Transaction Exchange rate",
    "Exchange gain",
    "Accrued interest",
    "Cost/Purchase price",
    "Transaction price",
    "Transaction gain",
    "Cost value",
    "Realized P/L",
    "Transaction value",
    "Settlement amount in account currency",
    "Place of execution",
    "Third-party executions",
    "Foreign Financial Transaction Tax",
]
SC_trans_header_template = []
JP_trans_header_template = []
BOS_trans_header_template = []
LGT_trans_header_template = []
UOB_trans_header_template = []
UBP_trans_header_template = []
JSS_trans_header_template = []